### ISSUE TITLE
Next feature todo

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/nextjs-ssr-real-world-app-example#7]
- [ ] Feature Sitemap / Robots.txt
- [ ] PWA / Offline Support
- [ ] Improve Pagination (show only 5 numbers with next/previous)
- [ ] Reflect the tabs, pagination and tags to URL params i.e. `?page=1&tag=reactjs&tab=global`
- [ ] Skeleton UI loading
